config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  namespace :admin do
    root 'home#index'
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'
    resources :carousel_images, only: [:index, :new, :create, :edit, :update, :destroy]
    

  end



resources :posts
# config/routes.rb
resources :ministries do
  patch 'update_order', on: :collection
end


  get 'admin/login', to: 'admin/sessions#new', as: :new_admin_session
  post 'admin/login', to: 'admin/sessions#create', as: :admin_session
  delete 'admin/logout', to: 'admin/sessions#destroy', as: :destroy_admin_session

  # Пример маршрута для админ-панели
  get 'admin/dashboard', to: 'admin/dashboard#index', as: :admin_dashboard

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_footer.html.erb
<footer class="footer-bg text-gray-500 bg-gray-300 py-10 mt-auto fade-in fade-in-delay-2 sticky top-0">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-4">
            <h2 class="text-xl font-bold">Ethiopian Evangelical Church Bonn</h2>
        </div>
        <div class="flex gap-5 justify-center mb-4">
            <a target="_blank" href="https://www.facebook.com/people/Ethiopian-evangelical-Church-in-BonnGermany/61570843404858/" class="social-icon">
                <i class="text-2xl fab fa-facebook-f hover:text-gray-800"></i>
            </a>
            <a target="_blank" href="https://wa.me/491727510678" class="social-icon">
                <i class="text-2xl fab fa-whatsapp hover:text-gray-800"></i>
            </a>
            <a target="_blank" href="https://www.youtube.com/@ethiopianevangelicalchurchbonn" class="social-icon">
                <i class="text-2xl fab fa-youtube hover:text-gray-800"></i>
            </a>
            <a target="_blank" href="https://www.tiktok.com/@ethiopianchurchbonn" class="social-icon">
            <i class="text-2xl fab fa-tiktok hover:text-gray-800"></i>
        </a>
        </div>
        <div class="text-center">
            <p class="font-light">&copy; 2025 Ethiopian Evangelical Church Bonn. <br> All rights reserved.</p>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-white sticky top-0 z-50 border-b border-gray-300 shadow-md" id="header">
    <div class="max-w-7xl mx-auto flex justify-between items-center py-4 px-4">
        <div class="flex items-center">
            <a href="/" class="transition duration-200 ease-in-out text-black hover:text-teal-500">
                <img class="h-8" src="<%= asset_path('Christian_cross.svg') %>" alt="Logo">
            </a>
        </div>
        <div class="flex items-center md:hidden">
            <button id="menu-toggle" class="text-black focus:outline-none">
                <!-- Hamburger Icon -->
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path id="line1" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16"></path>
                    <path id="line2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 12h16"></path>
                    <path id="line3" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 18h8"></path>
                </svg>
            </button>
        </div>
        <nav id="menu" class="hidden md:flex flex-grow justify-center space-x-10">
            <a href="/" class="transition duration-200 ease-in-out text-black hover:text-teal-500">Home</a>
            <a href="<%= posts_path %>" class="transition duration-200 ease-in-out text-black hover:text-teal-500">Blog</a>
            <a href="<%= ministries_path %>" class="transition duration-200 ease-in-out text-black hover:text-teal-500">Ministries</a>
            <a href="/#contact-us-id" class="transition duration-200 ease-in-out text-black hover:text-teal-500">Contact Us</a>
        </nav>
        <div class="relative hidden md:block">
            <div id="user-info">
                <% if session[:user_id] %>
                    <% user = User.find_by(id: session[:user_id]) %>
                    <% if user %>
                    <p><%= user.name %> <span class="text-gray-400">(Owner)</span></p>
                    <%= link_to 'Logout', admin_sessions_destroy_path, method: :delete, class: "text-red-500" %>
                    <% else %>
                    <% session.delete(:user_id) %>
                    <%= link_to 'Login', admin_sessions_new_path, class: "transition duration-200 ease-in-out text-black hover:text-teal-500" %>
                    <% end %>
                <% else %>
                    <%= link_to 'Login', admin_sessions_new_path, class: "transition duration-200 ease-in-out text-black hover:text-teal-500" %>
                <% end %>
            </div>
        </div>
    </div>

    <!-- Mobile Menu -->
    <nav id="mobile-menu" class="mt-16 py-6 md:hidden bg-white shadow-md hidden absolute top-0 left-0 w-full">
        <div class="flex flex-col items-center gap-3">
            <a href="/" class="py-2 transition duration-200 ease-in-out text-black hover:text-teal-500">Home</a>
            <a href="<%= posts_path %>" class="py-2 transition duration-200 ease-in-out text-black hover:text-teal-500">Blog</a>
            <a href="<%= ministries_path %>" class="py-2 transition duration-200 ease-in-out text-black hover:text-teal-500">Ministries</a>
            <a href="/#contact-us-id" class="py-2 transition duration-200 ease-in-out text-black hover:text-teal-500">Contact Us</a>

            <div class="py-2 text-center mt-5">
                <% if session[:user_id] %>
                <% user = User.find_by(id: session[:user_id]) %>
                <% if user&.admin? %>
                    <p class='bg-slate-100 p-3 rounded-lg mb-3'><%= user.name %> <span class="text-gray-400">(Owner)</span></p>
                <%= link_to 'Logout', admin_sessions_destroy_path, method: :delete, class: "text-red-500" %>
                <% end %>
                <% else %>
                <%= link_to 'Login', admin_sessions_new_path, class: "mt-5 transition duration-200 ease-in-out text-black rounded-xl hover:bg-gray-200 bg-gray-300 px-5 py-2" %>
                <% end %>     
            </div>
        </div>
    </nav>
</header>

<style>
/* Стили для бургера */
#menu-toggle svg path {
    transition: all 0.3s ease;
}

/* Стиль для открытия (переход на крестик) */
#menu-toggle.open #line1 {
    transform: translateY(6px) scaleX(0.8);
}

#menu-toggle.open #line2 {
    opacity: 0;
}

#menu-toggle.open #line3 {
    transform: translateY(-6px) scaleX(0.8);
}

/* Стандартное состояние (до открытия) */
#menu-toggle svg path {
    transform-origin: center;
}

</style>

<script>
document.getElementById('menu-toggle').addEventListener('click', function() {
    this.classList.toggle('open');
    document.getElementById('mobile-menu').classList.toggle('hidden'); // Показываем/скрываем меню
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evangelical Church in Bonn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application.tailwind", "data-turbo-track": "reload" %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.15.0/Sortable.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>

    <% unless ['edit', 'new'].include?(action_name) %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>